### PR TITLE
When switch to dark mode every page should switch

### PR DESCRIPTION
**Pull request by ArchismanKarmakar**
## Issue
#80 

## Description

When switch to dark mode every page should switch. But all the pages are messed up right now. So I just implemented the code with index pages of both languages. Same can also be done for other pages once corrected.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ArchismanKarmakar** [comment]
> ## Issue
> 
> #80
> ## Description
> 
> When switch to dark mode every page should switch. But all the pages are messed up right now. So I just implemented the code with index pages of both languages. Same can also be done for other pages once corrected.
> 
>     * [x]  Bug fix (non-breaking change which fixes an issue)
> 
>     * [x]  New feature (non-breaking change which adds functionality)
> 
>     * [x]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> 
>     * [ ]  Documentation change
> 
> 
> ## Checklist:
> 
>     * [x]  My code follows the style guidelines of this project
> 
>     * [x]  The app runs properly
> 
>     * [x]  I have performed a self-review of my own code
> 
>     * [x]  I have formatted and commented my code, particularly in hard-to-understand areas
> 
>     * [x]  I have made corresponding changes to the documentation
> 
>     * [x]  My changes generate no new warnings

#80 @mohit200008 I just implemented the code in index.html of both the languages. As all other pages are messed up right now, I didn't make changes to it. The same thing can be applied once the pages are ready

**Comment by mohit200008** [comment]
The file structure may not be changed because the css will have to be modified accordingly.

**Comment by ArchismanKarmakar** [comment]
> The file structure may not be changed because the css will have to be modified accordingly. 
> 

Yeah, that's why I created a item in local storage called "ui". It will be used to store the UI Mode value(dark or light). Body onload can be used to call a function that checks and switches to light and dark automatically.

**Comment by mohit200008** [comment]
Can you share a demo of it ???

**Comment by ArchismanKarmakar** [comment]
https://user-images.githubusercontent.com/92569441/147847251-027a60d5-1bc3-4be9-81de-ceac91c262f6.mp4

Please ignore the glitch. Actually a lot of projects were running together so recording at that time created the glitch.

**Pull request merged**
