### PR TITLE
navbar css put in a different file

### LINKED ISSUE #93: Putting the navbar css in a single file
# Description
The navbar is present in almost every page and its same css is written separately for every page. So if we want to make to the navbar design we have to modify so may files. It good to put all the css code in a single file and use it in different places

### LINKED ISSUE #95: While adding a question in question form its cloning the first question
# Description
When add question option is clicked, it is cloning the first question while it should make a blank form for adding question

https://user-images.githubusercontent.com/70333141/148388549-499e7b1b-b7c1-42d5-824e-cb4b25fe758a.mp4

You can see that the exact question is copied instead of opening a blank form

### PR DESCRIPTION
**Pull request by shmiitg**
## Issue
Fixes #93 
Fixes #95 

## Description
I have put the navbar css in single file and made sure everything is working fine. It shortens the code and makes the file structure more clean, organised and easy to maintain. Now to change the navbar design, only one file has to be changed instead of 4 files

### CODE REVIEW

**Comment by shmiitg** [comment]
Screenshot (378)
Screenshot (379)
Screenshot (380)

Navbar in every page still looks same

**Comment by shmiitg** [comment]
https://user-images.githubusercontent.com/70333141/148392988-dc0e109d-b9a5-4316-b57e-1176ede00563.mp4

**Comment by mohit200008** [comment]
both the errors are fixed right ????

**Comment by mohit200008** [comment]
@shmiitg

**Pull request merged**
