### PR TITLE
 Create a page to display the scores of students. #6 

### PR DESCRIPTION
**Pull request by ArchismanKarmakar**
#6 ISSUE please check sir

### CODE REVIEW

**Comment by mohit200008** [comment]
can you send a sc of the page ?????

**Comment by ArchismanKarmakar** [comment]
https://user-images.githubusercontent.com/92569441/145263924-615ff646-4c85-43e2-a0ef-fc8147ee8d2d.mp4



> can you send a sc of the page ?????

check the video sir

**Comment by mohit200008** [comment]
Good work @ArchismanKarmakar

**Comment by ArchismanKarmakar** [comment]
> Good work @ArchismanKarmakar

thanks sir.

**Comment by ArchismanKarmakar** [comment]
> Good work @ArchismanKarmakar

i had to created the pie.css myself, you can change the color scheme, and p$$ class for percentage and also remove the over50 for p<50%

**Comment by mohit200008** [comment]
You have to remove the cards from the home page and create another page for the cards

**Comment by ArchismanKarmakar** [comment]
> Good work @ArchismanKarmakar

sir can you please tell me what is the overall points you gave me for this?

**Comment by ArchismanKarmakar** [comment]
> You have to remove the cards from the home page and create another page for the cards

subject cards?

**Comment by mohit200008** [comment]
That will be 

> > Good work @ArchismanKarmakar
> 
> sir can you please tell me what is the overall points you gave me for this?

That cant be disclosed right now,

**Comment by ArchismanKarmakar** [comment]
> That will be
> 
> > > Good work @ArchismanKarmakar
> > 
> > 
> > sir can you please tell me what is the overall points you gave me for this?
> 
> That cant be disclosed right now,

okay

**Comment by ArchismanKarmakar** [comment]
> You have to remove the cards from the home page and create another page for the cards

sir please upload a screenshot where i need to remove it

**Comment by mohit200008** [comment]
On the navbar you have to add an additional link named Subjects and there you have to add the page you showed in the video

**Comment by mohit200008** [comment]
And on the home page above the navigation panel you will see subject cards , You have to remove those

**Comment by ArchismanKarmakar** [comment]
> 

doing

**Comment by mohit200008** [comment]
Remove the percentage from the subject cards , Just the cards are enough

**Comment by mohit200008** [comment]
Rest you're doing good

**Comment by mohit200008** [comment]
Hope you understood what you have to do

**Comment by ArchismanKarmakar** [comment]
> Hope you understood what you have to do

sir please check the PR #25

**Comment by ArchismanKarmakar** [comment]
> > Hope you understood what you have to do
> 
> sir please check the PR #25

please wait sir i thing the last pr you accepted removed the CSS from english one

**Pull request merged**
