### PR TITLE
 Issue updated/solution: Create a suitable About section above the subject cards. #4 

### PR DESCRIPTION
**Pull request by ArchismanKarmakar**

### CODE REVIEW

**Comment by mohit200008** [comment]
please can you share some screen shots

**Comment by ArchismanKarmakar** [comment]
> please can you share some screen shots

**Comment by mohit200008** [comment]
>The third picture in the carousel looks blurry please change that
> © 2021 Gam-Learn Ltd. All Rights Reserved. below contact us should be removed and also remove developed by ...
> And navigation panel can be like a heading to the footer and the background can be gray or something similar to white which also goes with the color of the website
 Rest you have done a great job!

**Comment by ArchismanKarmakar** [comment]
> > The third picture in the carousel looks blurry please change that
> > © 2021 Gam-Learn Ltd. All Rights Reserved. below contact us should be removed and also remove developed by ...
> > And navigation panel can be like a heading to the footer and the background can be gray or something similar to white which also goes with the color of the website
> > Rest you have done a great job!

Done sir, I did what you said

**Pull request merged**
