### PR TITLE
Added a form just frontend to add question to database

### LINKED ISSUE #36: Form for adding more questions  in a particular subjects
Create a form for adding new questions  to the database . It should have question, 3 options and chose subject option. Only frontend has to be created for now.

### PR DESCRIPTION
**Pull request by ShivaRapolu01**
## Issue
Fixes #36 

## Description

Added a form just frontend to add question to database

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mohit200008** [comment]
Can you provide a sc ???

**Comment by ShivaRapolu01** [comment]
yeah @mohit200008  !
image

**Comment by mohit200008** [comment]
the whole website is following a white color theme as you can see
Its better if the form for the question also follows the same

**Comment by mohit200008** [comment]
And the form should cover page to some extend

**Comment by ShivaRapolu01** [comment]
Yeah will work on this

**Comment by ShivaRapolu01** [comment]
Please have a look at this design
image

**Comment by ShivaRapolu01** [comment]
@mohit200008 The + button functionality is not added as only front-end has to be created. Also Please reopen #2  issue
Replace the cover photo with a Carousel in the home page  , I want to work on this

**Comment by shmiitg** [comment]
> @mohit200008 The + button functionality is not added as only front-end has to be created. Also Please reopen #2 issue Replace the cover photo with a Carousel in the home page , I want to work on this

The + button functionality can be enabled with javascript which is a part of front-end

**Comment by ShivaRapolu01** [comment]
Yeah! I will add the functionality too then

**Comment by mohit200008** [comment]
> Please have a look at this design image

->The design actually is not that appealing because the whole website follows a white color scheme 
-> The objective is that , there should be  a section on the subjects page saying add a question and a form pops up blurring the background where user can enter the question details and the question is added to that subject with the options. This section could be at the bottom above the footer.

**Comment by ShivaRapolu01** [comment]
Ok now I get it

**Pull request closed without merging**
