### PR TITLE
auth system using firebase

### LINKED ISSUE #7: Use firebase authentication for login/signup
. we want this function to implement in such a way that when someone enters his/her credentials,  He/She should be redirected to the home page on signup  and his credentials should be shown on the top also stored on the database.  And validate while logging in and then redirect to home page.

### PR DESCRIPTION
**Pull request by shmiitg**
## Issue
Fixes #7 

## Description

1. Added user authentication using firebase.
2. The logged in user can see his/her email in home page.
3. After logging in , user is redirected to home page.
4. After signup, user is redirected to home page

For logged in user: Logout button is shown which redirects to login page and email is shown
Screenshot (293)_LI

For logged out user: Login button is shown instead of logout which redirects to login page and no credentials are show
Screenshot (294)_LI

### CODE REVIEW

**Comment by mohit200008** [comment]
The credentials should be visible beside the logout button on the navbar

**Comment by shmiitg** [comment]
> The credentials should be visible beside the logout button on the navbar

ok sir I will do it, won't take much time.

**Comment by shmiitg** [comment]
job is done
please check 

For logged in user
Screenshot (301)_LI


For logged out user
Screenshot (300)_LI

**Comment by mohit200008** [comment]
Good work @shmiitg

**Comment by mohit200008** [comment]
Its working Without any errors right ??

**Comment by shmiitg** [comment]
> Its working Without any errors right ??

Yes its working fine..I checked it multiple times

**Comment by mohit200008** [comment]
On the readme you can see the email and password , Enter it in the firebase so that anyone  for now could enter those credentials and enter the website. Without login Subjects page should be hidden.

**Comment by shmiitg** [comment]
> On the readme you can see the email and password , Enter it in the firebase so that anyone for now could enter those credentials and enter the website. Without login Subjects page should be hidden.

The user email and password are stored in the database. I will hide the subjects page. By subjects page you mean this?
Screenshot (302)

**Comment by shmiitg** [comment]
> On the readme you can see the email and password , Enter it in the firebase so that anyone for now could enter those credentials and enter the website. Without login Subjects page should be hidden.

The user email and password are stored in the database. I will hide the subjects page. By subjects page you mean I have to hide this option right?
Screenshot (303)_LI

**Comment by shmiitg** [comment]
Done sir
For logged in users
Screenshot (304)_LI
For logged out users
Screenshot (305)_LI

* Also logged users get redirected to login page if they try to visit the subject page by changing the url directly

**Comment by shmiitg** [comment]
For the data of signed up users you can see the same database where questions are put

**Comment by mohit200008** [comment]
This has merge conflicts , i suggest you review the code one more time and send a pr again.
Otherwise its great work

**Comment by shmiitg** [comment]
I think that arrived because of the last mege as earlier it was not there. I will resolve it.

**Comment by shmiitg** [comment]
I resolved them, you can check now

**Pull request merged**
