### PR TITLE
link on navbar for scores

### LINKED ISSUE #56: Add a link on navbar for scores
Add a link on navbar for showing the scores of students. After the game ends the user redirects to the scores page.

### PR DESCRIPTION
**Pull request by shmiitg**
## Issue
Fixes #56 

https://user-images.githubusercontent.com/70333141/147323502-49a770be-224a-4d63-970a-dcd4ce835a56.mp4

After the game ends the user will be redirected to the scores page (this was done by me previously)

### CODE REVIEW

**Comment by mohit200008** [comment]
scores have to be fetched from database of all users

**Comment by shmiitg** [comment]
> scores have to be fetched from database of all users

ok... so I have to change the content of score page right? by displaying all the score rather than only previous scores

**Comment by mohit200008** [comment]
it can be like user can view his/her scores also and other user's scores too.It will be considered as a intermediate issue

**Comment by shmiitg** [comment]
Screenshot (322)
The user-email and corresponding scores are visible which are being fetched from database. is this correct?

**Comment by shmiitg** [comment]
I have sorted the scores on the basis of time (latest to oldest) and created pr

**Pull request merged**
