### PR TITLE
Resolved minor changes

### PR DESCRIPTION
**Pull request by ShivaRapolu01**

### CODE REVIEW

**Comment by ShivaRapolu01** [comment]
I guess this issue comes under easy category and few additional points for pointing out this issue right?

**Comment by mohit200008** [comment]
yes

**Comment by mohit200008** [comment]
can you send a sc of the final layout and then we're good to go

**Comment by ShivaRapolu01** [comment]
image
image

**Comment by ShivaRapolu01** [comment]
ok?

**Comment by mohit200008** [comment]
yes

**Pull request merged**
