### PR TITLE
Resolved merge conflicts and redesigned cards

### PR DESCRIPTION
**Pull request by ShivaRapolu01**

### CODE REVIEW

**Comment by ShivaRapolu01** [comment]
Solves #3 
I guess this will come under medium category 🥲  because I had to change so many things, if possible please consider this as medium category issue  based upon my effort on the new creative design and grant marks accordingly 😄

**Comment by mohit200008** [comment]
It would be going against the rules but your effort won't go in vain. You'll be rewarded for it.

**Comment by ShivaRapolu01** [comment]
Thank you! please update code peak leaderboard

**Comment by ShivaRapolu01** [comment]
@mohit200008 Bhaiya kindly can you please say when will the leaderboard be updated with the points of this issue?

**Pull request merged**
