### PR TITLE
solved the login redirecting issue

### LINKED ISSUE #47: on login the page should be redirected to home page not subjects page
When user log in , the home page having the carousel should appear not the subjects page.

### PR DESCRIPTION
**Pull request by ShivaRapolu01**
## Issue
Fixes #47 

## Description

Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
You can write manually also

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] The app runs properly
- [x] I have performed a self-review of my own code
- [x] I have formatted and commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by ShivaRapolu01** [comment]
@mohit200008

**Comment by mohit200008** [comment]
is it showing the right page now ????

**Comment by mohit200008** [comment]
@ShivaRapolu01

**Comment by ShivaRapolu01** [comment]
yes

**Comment by ShivaRapolu01** [comment]
I have cross-checked it now , it is showing correct page

**Comment by ShivaRapolu01** [comment]
image

**Comment by ShivaRapolu01** [comment]
@mohit200008 please update the  points for solving this issue.

**Pull request merged**
